from supabase import create_client

# Substitua pelas suas chaves do Supabase
SUPABASE_URL = "rimuhgulxliduugenxro"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbXVoZ3VseGxpZHV1Z2VueHJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTM1NTc1OCwiZXhwIjoyMDc0OTMxNzU4fQ.mcUWnpowzRom6cZt7amJqRqo-qNWQS6MBibIZbvFS0s"

supabase = create_client(rimuhgulxliduugenxro, sb_secret_k543j2NP_ErAi9Yoyn1Keg_aMyUG4F-)
